apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: spring-sql-jpa
  name: spring-sql-jpa
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: spring-sql-jpa
  sessionAffinity: None
  type: ClusterIP
